"""Writes integration_test/fixtures.g.dart from test/fixtures.

Tests on a phone or emulator can't read files from the repository, so the
tiny test manual is embedded in the test app. The output is committed (so
`flutter analyze` finds it); run this from app/ after changing
test/fixtures. The emulator workflow runs it too.
"""

import base64
from pathlib import Path

root = Path("test/fixtures")
lines = [
    "// Generated by integration_test/make_fixtures.py from test/fixtures. Do not edit.",
    "",
    "const fixtureFiles = <String, String>{",
]
for path in sorted(p for p in root.rglob("*") if p.is_file()):
    data = base64.b64encode(path.read_bytes()).decode()
    lines.append(f"  '{path.relative_to(root).as_posix()}': '{data}',")
lines += ["};", ""]
Path("integration_test/fixtures.g.dart").write_text("\n".join(lines))
